#execution_env = remote
execution_env = local

appURL = https://tutorialsninja.com/demo/index.php?route=common/home
grid.url=http://10.201.181.240:4444
email = anikettraining@gmail.com
password = test@1234
searchProductName = iPhone
edge.driver.path=C:\\Users\\Aniket\\WebDrivers\\msedgedriver.exe